<Project>
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Version>2.7.2</Version>
    <Company>duhaoda</Company>
    <Copyright>LightBulb (c) Oleksii Holub (MIT). Eye-care modifications (c) 2026 duhaoda.</Copyright>
    <Nullable>enable</Nullable>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ILLinkTreatWarningsAsErrors>false</ILLinkTreatWarningsAsErrors>
  </PropertyGroup>
</Project>
